<div id="footer-menu" style="display:none;">
	<ul>
		<li class="footer-menu-top"><?php echo $this->__('Your HR space') ?></li>
		<li><?php echo $this->__('Your Informations') ?></li>
		<li><?php echo $this->__('Your Orders') ?></li>
		<li><?php echo $this->__('Your Diagnostic') ?></li>
		<li><?php echo $this->__('Your Newsletters') ?></li>
		<li><?php echo $this->__('HR Community') ?></li>
	</ul>
</div>