<div class="block block-login">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post">
		<div class="block-content">
            <label for="mini-login"><?php echo $this->__('Username or email') ?></label><input type="text" name="login[username]" id="mini-login" class="input-text" />
            <label for="mini-password"><?php echo $this->__('Password:') ?></label><input type="password" name="login[password]" id="mini-password" class="input-text" />
            <div class="actions">
                <button type="submit" class="button"><span><span><?php echo $this->__('Connexion') ?></span></span></button>
            </div>
        </div>
    </form>
</div>