<div class="block block-login">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post">
		<div class="block-content">
            <label for="mini-login"><?php echo $this->__('Username or email') ?></label><input type="text" name="login[username]" id="mini-login" class="input-text" />
            <label for="mini-password"><?php echo $this->__('Password:') ?></label><input type="password" name="login[password]" id="mini-password" class="input-text" />
            <div class="actions">
                <button type="submit" class="button"><span><span><?php echo $this->__('Connexion') ?></span></span></button>
            </div>
        </div>
    </form>
</div>
<div id="register-box" class="block block-register">
	<div class="block-content">
		<span><?php echo $this->__('Are you a new customer ?'); ?></span>
		<button type="submit" class="button"><span><span><?php echo $this->__('Register'); ?></span></span></button>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
	Event.observe(window, 'load', function() {
		$('account-box').hide();
	});
	$('register-box').observe('click', function(event){
		if($('account-box').visible())
			$('account-box').hide();
		else
			$('account-box').show();
	});
	$('login-link').observe('click', function(event){
		if($('account-box').visible())
			$('account-box').hide();
		else
			$('account-box').show();
	})
	/*.observe('mouseout', function(event){
		$('account-box').hide();
	})*/;
//]]>
</script>