<form method="post" action="">
	<div class="col-1 addresses-primary">
	    <h2><?php echo $this->__('Default Addresses') ?></h2>
	    <ol>
	    <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
	        <li class="item">
	            <h3><?php echo $this->__('Default Billing Address') ?></h3>
	            <input type="radio" name="id" value="<?php echo $_pAddsses; ?>" />
	            <address>
	                <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
	            </address>
	       </li>
	    <?php else: ?>
	        <li class="item">
	            <h3><?php echo $this->__('Default Billing Address') ?></h3>
	            <?php echo $this->__('You have no default billing address in your address book.') ?>
	        </li>
	    <?php endif ?>
	
	    <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
	        <li class="item">
	            <h3><?php echo $this->__('Default Shipping Address') ?></h3>
	            <input type="radio" name="id" value="<?php echo $_pAddsses; ?>" />
	            <address>
	                <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
	            </address>
	        </li>
	    <?php else: ?>
	        <li class="item empty">
	            <h3><?php echo $this->__('Default Shipping Address') ?></h3>
	            <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
	        </li>
	    <?php endif ?>
	    </ol>
	</div>
	<div class="col-2 addresses-additional">
	    <h3><?php echo $this->__('Additional Address Entries') ?></h3>
	    <ol>
	    <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
	        <?php foreach($_pAddsses as $_address): ?>
	        <li class="item">
	        	<input type="radio" name="id" value="<?php echo $_address->getId(); ?>" />
	            <address>
	                <?php echo $this->getAddressHtml($_address) ?>
	            </address>
	        </li>
	        <?php endforeach; ?>
	    <?php else: ?>
	        <li class="item empty">
	            <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
	        </li>
	    <?php endif ?>
	    </ol>
	</div>
	<div>
     	<?php echo $this->getChildHtml('messages'); ?>
    </div>
	<div class="buttons-set">
		<div class="left-buttons">
			<button type="button" id="edit-address-button"><span><span><?php echo $this->__('Edit') ?></span></span></button>
			<button type="button" id="delete-address-button"><span><span><?php echo $this->__('Delete') ?></span></span></button>
		</div>
		<div class="right-buttons">
			<button type="button" id="add-address-button"><span><span><?php echo $this->__('Add an address') ?></span></span></button>
		</div>
	</div>
<form>
<script type="text/javascript">
//<![CDATA[
    $('add-address-button').observe('click', function(event){
    	var reloadurl = '/customer/address/new';
    	new Ajax.Request(reloadurl, {
    		method: 'post',
    		onSuccess: function(transport) {
    			$('customer-address-book').innerHTML = '';
    			$('customer-address-book').innerHTML = transport.responseText;
    			var dataForm = new VarienForm('form-validate', true);
    			transport.responseText.evalScripts();
			}
    	});
    });
    $('edit-address-button').observe('click', function(event){
    	var loadurl = '/customer/address/edit/id/'+$$('input:checked')[0].value;
    	new Ajax.Request(loadurl, {
    		method: 'post',
    		onSuccess: function(transport) {
    			$('customer-address-book').innerHTML = '';
    			$('customer-address-book').innerHTML = transport.responseText;
    			transport.responseText.evalScripts();
    		}
    	})
    });
    $('delete-address-button').observe('click', function(event) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
        	loadurl = '<?php echo $this->getDeleteUrl() ?>id/'+$$('input:checked')[0].value;
        	new Ajax.Request(loadurl, {
    			method: 'post',
    			onSuccess: function(transport) {
    				$('customer-address-book').innerHTML = '';
    				$('customer-address-book').innerHTML = transport.responseText;
    				transport.responseText.evalScripts();
    			}
    		});
        }
    });
//]]>
</script>