<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div class="col2-set addresses-list">
	<div class="page-title title-buttons">
    	<h1><?php echo $this->__('Address Book') ?></h1>
	</div>
	<div id="customer-address-book">
		<?php echo $this->getChildHtml('address_book_list'); ?>
	</div>
</div>

<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>