<?php if($this->getItems()->getSize()): ?>
<div class="products">
    <div class="header"><p>Les produits associés <span>pour un résultat optimal</span></p></div>
        <?php foreach($this->getItems() as $_item): ?>
        <div class="product">
            <div class="photo_product">
                <img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(125) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" />
            </div>
            <div class="product_infos">
                <table>
                    <tr>
                        <td class="left">
                            <span>Illuminateur</span>
                            <p><?php echo $this->htmlEscape($_item->getName()) ?></p> 
                            <p>POWDER</p>
                            <p>poudre</p>
                        </td>
                        <td class="right"><p><?php echo $this->getPriceHtml($_item, true, '-related') ?></p></td>
                    </tr>
                </table>				
            </div>
            <div class="bottom_btn">
                <div class="fb_bg">
                </div>
                <div class="acheter"><a href="<?php echo $_item->getProductUrl() ?>">acheter</a></div>
            </div>
        </div>
        <div class="separator"></div>
        <?php endforeach ?>
    </div>
<?php endif ?>    