<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @copyright  Copyright (c) 2008-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div class="content-header">
	<table cellspacing="0">
		<tr>
			<td style="width:50%;"><h3><?php echo Mage::helper('newsletter')->__('Newsletter Subscribers') ?></h3></td>
			<td align="right">
				<button  type="button" class="scalable" onclick="window.location='<?php echo $this->getUrl('advancednewsletter_admin/*/new'); ?>'" style="">
					<span><?php echo Mage::helper('advancednewsletter')->__('Add subscriber') ?></span>
				</button>
				<button  type="button" class="scalable" onclick="window.location='<?php echo $this->getUrl('advancednewsletter_admin/*/sync'); ?>'" style="">
                <!--<button  type="button" class="scalable" onclick="window.location='<?php echo Mage::getUrl()?>mailchimp/index/index/key/<?php echo $this->getRequest()->getParam('key')?>/';" style="">-->
					<span><?php echo Mage::helper('advancednewsletter')->__('Advanced Newsletter / Mailchimp synchronization') ?></span>
				</button>
			</td>
		</tr>
	</table>
</div>
<div>
    <?php echo $this->getChildHtml('grid') ?>
</div>
<?php if(count($this->getQueueAsOptions())>0 && $this->getShowQueueAdd()): ?>
<div class="form-buttons">
	<select id="queueList" name="queue">
	<?php foreach ($this->getQueueAsOptions() as $_queue): ?>
		<option value="<?php echo $_queue['value'] ?>"><?php echo $_queue['label'] ?> #<?php echo $_queue['value'] ?></option>
	<?php endforeach; ?>
	</select>
	<button class="scalable" onclick="subscriberController.addToQueue();"><span><?php echo Mage::helper('newsletter')->__('Add to Queue'); ?></span></button>
</div>
<?php endif ?>
<script type="text/javascript">
<!--
	var subscriberController = {
		checkCheckboxes: function(controlCheckbox) {
			var elements = $('subscriberGrid').getElementsByClassName('subscriberCheckbox');
			elements.each(function(obj){
				obj.checked = controlCheckbox.checked;
			});
		},
		rowClick: function (e) {
			if(!Event.element(e).hasClassName('subscriberCheckbox')) {
				var elements = Event.findElement(e, 'tr').getElementsByClassName('subscriberCheckbox');
				if(elements.length != 1) {
					return;
				}
				elements[0].checked = !elements[0].checked;
			}
		},
		addToQueue: function () {
			var elements = $('subscriberGrid').getElementsByClassName('subscriberCheckbox');
			elements.push($('queueList'));
			var serializedElements = Form.serializeElements(elements, true);
			serializedElements.add = 'subscribers';
			serializedElements.form_key = FORM_KEY;
			var url = subscriberGridJsObject.url;

			new Ajax.Updater('subscriberGrid', url + '?ajax=1',
							 {parameters:  serializedElements,
							  evalScripts: true,
							  onComplete:subscriberGridJsObject.initGrid.bind(subscriberGridJsObject)});
		}
	}

	varienGlobalEvents.attachEventHandler('gridRowClick', subscriberController.rowClick.bind(subscriberController));
//-->
</script>
