<div class="dashboard">
    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    <div class="box-account box-info">
        <?php echo $this->getChildHtml('dashboard_informations') ?>
        <?php echo $this->getChildHtml('dashboard_orders') ?>
        <?php echo $this->getChildHtml('dashboard_diagnostic') ?>
        <?php echo $this->getChildHtml('dashboard_newsletter') ?>
        <?php echo $this->getChildHtml('dashboard_community') ?>
        <?php echo $this->getChildHtml('address') ?>
    </div>
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>
