<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Advancednewsletter
 * @copyright  Copyright (c) 2008-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>

<div id="an-subscribe">
    <div class="group-select">
        <div class="an-right">
                <img style="cursor:pointer;" id="advancednewsletter-cancel" onclick="window.Advancednewsletter.deactivate(); return false;" src="<?php echo $this->getSkinUrl('images/btn_window_close.gif'); ?>" />
        </div>
        <div class="head">
            <h4 align="center"><?php echo $this->__('Subscribe to newsletter') ?><a name="newsletter-box"></a></h4>
        </div>
        <form action="<?php echo $this->getUrl('advancednewsletter/index/subscribe/').'category/'.$this->getCategoryId().'/' ?>" method="post" id="advancednewsletter-form">
            <fieldset class="content">
                <legend><?php echo $this->__('Newsletter') ?></legend>
                <!--
                <?php if( $message = $this->getErrorMessage() ): ?>
                    <p class="error"><?php echo $message ?></p>
                <?php endif; ?>
                <?php if( $message = $this->getSuccessMessage() ): ?>
                    <p class="success"><?php echo $message ?></p>
                <?php endif; ?>
                -->
                <ul>
                <?php if(Mage::getStoreConfig('advancednewsletter/formconfiguration/segmentsstyle')=='none'): ?>
                <li>
                    <?php echo $this->__('Subscribe to') ?>
                    <?php
                    switch (Mage::getStoreConfig('advancednewsletter/formconfiguration/defaultsubscription'))
                    {
                        case 'all': echo $this->__("all news"); break;
                        case 'store_default': echo $this->__("store news"); break;
                        case 'category_default': echo $this->__("category news"); break;
                    }
                    ?>
                </li>
                <?php else:?>
                <li>
                <label for="segments_select="><?php echo $this->__('Select lists') ?><span class="required">*</span></label><br/>

                <?php if(Mage::getStoreConfig('advancednewsletter/formconfiguration/segmentsstyle')=='select'): ?>
                    <select class="required-entry" name="segments_select" id="segments_select" style="width:95%">
                    <?php foreach($this->getSegments() as $key => $segment): ?>
                        <?php if($this->checkSegmentforSelection($segment['value'])||$key==0) $selected='selected="selected"'; else $selected='';?>
                        <option <?php echo $selected;?> value="<?php echo $segment['value']; ?>"><?php echo $segment['label']; ?></option>
                    <?php endforeach; ?>
                    </select>
                </li>
                <?php endif; ?>

                <?php if(Mage::getStoreConfig('advancednewsletter/formconfiguration/segmentsstyle')=='multiselect'): ?>
                <li>
                    <select class="required-entry" name="segments_select[]" multiple="" size=5 id="segments_select" style="width:95%">
                    <?php foreach($this->getSegments() as $key => $segment): ?>
                        <?php if(!$this->checkSegmentforSelection($segment['value'])) $selected=''; else $selected='selected="selected"';?>
                        <option <?php echo $selected;?> value="<?php echo $segment['value']; ?>"><?php echo $segment['label']; ?></option>
                    <?php endforeach; ?>
                    </select>
                </li>
                <?php endif; ?>

                <?php if(Mage::getStoreConfig('advancednewsletter/formconfiguration/segmentsstyle')=='radio'): ?>
                <li>
                    <?php foreach($this->getSegments() as $key => $segment): ?>
                        <?php if($this->checkSegmentforSelection($segment['value'])||$key==0) $checked='checked="checked"'; else $checked='';?>
                        <input <?php echo $checked;?> type="radio" name="segments_select" value="<?php echo $segment['value']; ?>"><?php echo $segment['label']; ?></option><br />
                    <?php endforeach; ?>
                </li>
                <?php endif; ?>

                <?php if(Mage::getStoreConfig('advancednewsletter/formconfiguration/segmentsstyle')=='checkboxes'): ?>
                <?php foreach($this->getSegments() as $key => $segment): ?>
                    <?php if(!$this->checkSegmentforSelection($segment['value'])) $checked=''; else $checked='checked="checked"';?>
                    <input <?php echo $checked;?> type="checkbox" name="segments_select[]" value="<?php echo $segment['value']; ?>"> <?php echo $segment['label']; ?><br />
                <?php endforeach; ?>
                <?php endif; ?>

                <?php endif; ?>
                <?php if(!Mage::getStoreConfig('advancednewsletter/formconfiguration/displaynamecustomers')&&Mage::getSingleton('customer/session')->isLoggedIn()):?>
                <?php elseif(Mage::getStoreConfig('advancednewsletter/formconfiguration/displayname')): ?>
                <?php if(Mage::getStoreConfig('advancednewsletter/formconfiguration/displaysalutation')): ?>
                <li>
                <label><?php echo $this->__('Salutation') ?></label>
                <br />
                <select name="salutation_an" id="salutation_an" style="width:95%">
                    <option value="0"><?php echo Mage::getStoreConfig('advancednewsletter/formconfiguration/salutation1') ?></option>
                    <option value="1"><?php echo Mage::getStoreConfig('advancednewsletter/formconfiguration/salutation2') ?></option>
                </select>
                </li>
                <?php endif; ?>
                <li>
                <label for="firstname_an"><?php echo $this->__('First name') ?></label><br/>
                <input name="firstname_an" type="text" id="firstname_an" size="50" style="width:95%"/>
                </li>
                <li>
                <label for="lastname_an"><?php echo $this->__('Last name') ?></label><br/>
                <input name="lastname_an" type="text" id="lastname_an" size="50" style="width:95%"/>
                </li>
                <?php endif; ?>
                <?php if((Mage::getStoreConfig('advancednewsletter/formconfiguration/displayemailcustomers')&&Mage::getSingleton('customer/session')->isLoggedIn())||!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                <li>
                <label for="email_an"><?php echo $this->__('Email') ?><span class="required">*</span></label><br/>
                <input name="email_an" type="text" id="email_an" size="50" class="validate-email required-entry" style="width:95%"/>
                </li>
                <?php endif; ?>
                <?php if(Mage::getStoreConfig('advancednewsletter/formconfiguration/displayphone')): ?>
                <li>
                <label for="phone_an"><?php echo $this->__('Phone') ?></label>
                <input name="phone_an" type="text" id="phone_an" style="width:95%"/>
                </li>
                <?php endif; ?>
                <div class="button-set">
                    <button type="submit" class="button">
                        <span><span><?php echo $this->__('Subscribe') ?></span></span>
                    </button>
                </div>
            </fieldset>
            </form>
   </div>
</div>

<script type="text/javascript">
    var advancednewsletterForm = new AdvancednewsletterForm('advancednewsletter-form');
</script>


