<?php
/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()): ?>
        <?php foreach ($_additional as $_data): ?>
            <h3 class="header">
                <a href="#">
                    <p class="open">
                        <?php echo $this->htmlEscape($this->__($_data['label'])) ?>
                    </p>
                </a>
            </h3>
            <div class="text_container">
                <p class="contenu">
                    <?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                </p>
            </div>            
        <?php endforeach; ?>
<?php endif;?>
