<?php
/**
 * Product description template
 *
 * @see Mage_Catalog_Block_Product_View_Description
 */
?>
<?php $_description = $this->getProduct()->getDescription(); ?>
<?php if ($_description): ?>
    <h3 class="header">
        <a href="#">
            <p class="open">
                <?php echo $this->__('Details') ?>
            </p>
        </a>
    </h3>
    <div class="text_container">
        <p class="contenu">
            <?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_description, 'description') ?>
        </p>
    </div>    
<?php endif; ?>
