<?php
/**
 * @see Mage_Checkout_Block_Agreements
 */
?>

<?php if (!$this->getAgreements()) return; ?>
<form action="" id="checkout-agreements" onsubmit="return false;">
<ol class="checkout-agreements">
<?php foreach ($this->getAgreements() as $_a): ?>
    <li>
        <div title="<?php echo $this->__('Terms and Conditions') ?>" id="agreement-dialog" class="agreement-content"<?php echo ($_a->getContentHeight() ? ' style="height:' . $_a->getContentHeight() . '"' : '')?>>
            <?php if ($_a->getIsHtml()):?>
                <?php echo $_a->getContent() ?>
            <?php else:?>
                <?php echo nl2br($this->htmlEscape($_a->getContent())) ?>
            <?php endif; ?>
        </div>
        <p class="agree">
            <input type="checkbox" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" title="<?php echo $this->htmlEscape($_a->getCheckboxText()) ?>" class="checkbox" /><label for="agreement-<?php echo $_a->getId()?>"><?php echo $this->htmlEscape($_a->getCheckboxText()) ?></label>
        </p>
    </li>
<?php endforeach ?>
</ol>
</form>
<script type="text/javascript">
	$j("#agreement-dialog").dialog({
		modal:true,
		height:350,
		width:570,
		closeText:'fermer',
		autoOpen: false
		//buttons: {Ok: function(){$j(this).dialog('close')}}
	});
	$j('#agreement-<?php echo $_a->getId()?>').click(function(){
		if($j(this).attr('checked')){
			$j("#agreement-dialog").dialog('open');
		}
		else {
			$j(this).attr('checked', false);
		}
	});
</script>