<div class="block block-progress">
    <div class="block-content">
        <div>
        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
            <h3 class="complete">
                <?php echo $this->__('Billing Address') ?>
            </h3>
            <div class="complete">
                <address><?php echo $this->getBilling()->format('html') ?></address>
            </div>
            <p>
            	<a href="#payment" onclick="checkout.accordion.openSection('opc-shipping');return false;"><?php echo $this->__('Change') ?></a>
            </p>
        </div>
        <?php endif; ?>
		<div>
        <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
            <h3 class="complete">
                <?php echo $this->__('Shipping Address') ?> 
            </h3>
            <div class="complete">
                <address><?php echo $this->getShipping()->format('html') ?></address>
            </div>
            <p>
            	<a href="#payment" onclick="checkout.accordion.openSection('opc-shipping');return false;"><?php echo $this->__('Change') ?></a>
            </p>
        <?php endif; ?>
		</div>
        <div>
        <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
            <h3 class="complete">
                <?php echo $this->__('Your gift message') ?>
            </h3>
            <div class="complete">
                <address><?php echo $this->getShipping()->format('html') ?></address>
            </div>
            <p>
            	<a href="#payment" onclick="checkout.accordion.openSection('opc-shipping');return false;"><?php echo $this->__('Change') ?></a>
            </p>
        <?php endif; ?>
        </div>
    </div>
</div>
