<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<script type="text/javascript">
	var params = {
		quality: "high",
		scale: "noscale",
		wmode: "transparent",
		allowscriptaccess: "always",
		bgcolor: "#1A1216"
	};
	var flashvars = {
		siteXML: "http://rubinstein.local/media/flash/xml/site.xml",
		lg : "fr"
	};
	var attributes = {
		id: "flashcontent",
		name: "flashcontent"
	};
	swfobject.embedSWF("http://rubinstein.local/media/flash/main.swf", "flashcontent", "1024", "374", "10.0.0", "http://rubinstein.local/media/flash/expressInstall.swf", flashvars, params, attributes);
</script>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($_imgUrl): ?>
    <?php echo $_imgHtml ?>
<?php endif; ?>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
    <?php endif; ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
