<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php $_links = $this->getLinks(); ?>
<div class="account-box">
	<div class="my-account">
		<?php echo $this->__('My Account'); ?>
	</div>
	<div class="my-customer">
	<?php if($this->helper('customer')->isLoggedIn()): ?>
		<p><?php echo $this->__('Hello') ?></p>
		<p><?php echo $this->helper('customer')->getCustomer()->getFirstname(); ?></p>
	<?php endif; ?>
	<?php if(count($_links)>0): ?>
	<ul class="links"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
	    <?php foreach($_links as $_link): ?>
	        <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
	    <?php endforeach; ?>
	</ul>
	<?php endif; ?>
	</div>
</div>
