<div class="box-title">
	<h3><?php echo $this->__('Contact Information') ?></h3>
	<span><?php echo $this->__('If you want, you can edit your informations.'); ?></span>
</div>
<div class="box">
    <div class="box-content">
        <div>
        	<label for="email"><?php echo $this->__('Your email :'); ?></label>
        	<p id="email"><?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?></p>
        </div>
        <div>
        	<p><?php echo $this->__('Your password :') ?></p>
        	<p>********</p>
        </div>
        <div>
        	<?php echo $this->getChildHtml('messages'); ?>
        </div>
        <div class="buttons-set">
			<div class="right-buttons">
				<button type="button" id="edit-account-button"><span><span><?php echo $this->__('Edit your informations') ?></span></span></button>
			</div>
		</div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    $('edit-account-button').observe('click', function(event){
    	var reloadurl = '/customer/account/edit';
    	new Ajax.Request(reloadurl, {
    		method: 'post',
    		onSuccess: function(transport) {
    			$('customer-account-info').innerHTML = '';
    			$('customer-account-info').innerHTML = transport.responseText;
    			transport.responseText.evalScripts();
			}
    	});
    });
//]]>
</script>