<div class="account-item">
	<div class="account-item-image"><img src="<?php echo $this->getItemImageFile(); ?>" alt="<?php echo $this->getItemImageAlt() ?>" /></div>
	<h2><?php echo $this->getItemTitle(); ?></h2>
	<p class="account-item-content">
		<?php echo $this->getItemContent(); ?>
	</p>
	<a href="<?php echo $this->getItemLinkUrl(); ?>"><span><span><?php echo $this->getItemLinkLabel(); ?></span></span></a>
</div>